### ISSUE TITLE
Changelog not up to date

### ISSUE THREAD

**Issue by dbjz** [TheJumpCloud/MDM-Prestage-User-Enrollment#10]
The current Changelog does not reflect the changes made with the current version of the scripts.  By looking at the changes It looks like the only change made was verifying that the Daemon is there before removal.

**Comment by jworkmanjc** [comment]
Hi @dbjz,

Thanks for the note, I updated the Change log with notes from the last pull request, you are right it was a change to validate the daemon before removal.
