### ISSUE TITLE
DepNotify failing to download/install

### ISSUE THREAD

**Issue by dbjz** [TheJumpCloud/MDM-Prestage-User-Enrollment#19]
It seems that the Download of DepNotify is failing.  Upon further investigation it looks like the SSL cert has expired for the url of the package.  Not really sure where to go from there. I will attach a log from the script but it just says downloading and retrying over and over again. 
[debug_depnotify.log](https://github.com/TheJumpCloud/MDM-Prestage-User-Enrollment/files/13368047/debug_depnotify.log)

**Comment by olaplex-tibby** [comment]
I'm updating my script and adding --insecure before the download URL as a temporary fix

jumpcloud_bootstrap_template.sh
Line 181
current: curl --silent --output /tmp/DEPNotify-1.1.6.pkg "https://files.nomad.menu/DEPNotify.pkg" >/dev/null
fixed: curl --silent --output /tmp/DEPNotify-1.1.6.pkg --insecure "https://files.nomad.menu/DEPNotify.pkg" >/dev/null

**Comment by jworkmanjc** [comment]
Also closing, again, looks like the host for DEPNotify needed to update a cert. That's been done but thanks for the conversation as a temp workaround.
