### ISSUE TITLE
SSL Certificate error on the website used to download DEPNotify

### ISSUE THREAD

**Issue by olaplex-tibby** [TheJumpCloud/MDM-Prestage-User-Enrollment#20]
https://github.com/TheJumpCloud/MDM-Prestage-User-Enrollment/blob/630510f0d655b1534ecf461e94a4910a705204ee/jumpcloud_bootstrap_template.sh#L181C5-L181C104

**Comment by olaplex-tibby** [comment]
add --insecure before the URL

**Comment by jworkmanjc** [comment]
I'm going to close this issue, there was an ssl cert that needed to be renewed, it looks like that has been resolved.
