### ISSUE TITLE
ORG_ID is not available in jcagent.conf

### ISSUE THREAD

**Issue by olaplex-tibby** [TheJumpCloud/MDM-Prestage-User-Enrollment#21]
https://github.com/TheJumpCloud/MDM-Prestage-User-Enrollment/blob/630510f0d655b1534ecf461e94a4910a705204ee/jumpcloud_bootstrap_template.sh#L472C5-L476C40

**Comment by jworkmanjc** [comment]
I'm going to close this issue, I believe it to be resolved in #22.
